name: CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm clean-install
      - name: Check formatting
        run: npx prettier . --ignore-unknown --list-different
      - name: Check linting
        # "env" is required for the step since "npx next typegen" command line program loads Next.js's configuration file where the check for the correct environment variables happens
        # "npx next typegen" command line program must be run before linting to generate types required for linting
        # Dummy values are enough since the purpose is just to check linting
        env:
          SUPABASE_CONNECTION_STRING: https://supabase.com
          SUPABASE_URL: https://supabase.com
          SUPABASE_PUBLISHABLE_KEY: test
          BETTER_AUTH_SECRET: test
          BETTER_AUTH_URL: https://better-auth.com
          GEMINI_API_KEY: test
          GOOGLE_EMAIL: test@test.com
          GOOGLE_APP_PASSWORD: test
          FINNHUB_API_KEY: test
        run: |
          npx next typegen
          npm run lint:check
      - name: Check spelling
        run: npm run spell:check
