name: Code quality
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  checks:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Generate TypeScript definitions for Next.js
        # Required for the step. Dummy values are enough
        env:
          SUPABASE_CONNECTION_STRING: https://supabase.com
          SUPABASE_URL: https://supabase.com
          SUPABASE_PUBLISHABLE_KEY: test
          BETTER_AUTH_SECRET: test
          BETTER_AUTH_URL: https://better-auth.com
          GEMINI_API_KEY: test
          GOOGLE_EMAIL: test@test.com
          GOOGLE_APP_PASSWORD: test
          FINNHUB_API_KEY: test
        run: npx next typegen
      - name: Check formatting
        run: npm run format:check
      - name: Check linting
        run: npm run lint:check
      - name: Check spelling
        run: npm run spell:check
