name: Pull request code quality
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm clean-install
      - name: Lint commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
      - name: Spell check commit messages
        run: |
          git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:%s%n%b%n%n > commit-messages.txt
          npx cspell commit-messages.txt --no-progress --no-summary
      - name: Spell check files
        uses: streetsidesoftware/cspell-action@v8.1.2
      - name: Get files to check formatting
        id: get-files-to-check-formatting
        uses: tj-actions/changed-files@v47.0.1
      - name: Check files formatting
        if: steps.get-files-to-check-formatting.outputs.any_changed == 'true'
        run: npx prettier --ignore-unknown --list-different ${{ steps.get-files-to-check-formatting.outputs.all_changed_files }}
      - name: Get files to lint
        id: get-files-to-lint
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: '**/*.{mjs,ts,mts,tsx}'
      - name: Lint files
        if: steps.get-files-to-lint.outputs.any_changed == 'true'
        # `env` is required for the step since `npx next typegen` command line program loads Next.js's configuration file where the check for the correct environment variables happens
        # `npx next typegen` command line program must be run before linting to generate types required for linting
        # Dummy values are enough since the purpose of the step is just to lint
        env:
          SUPABASE_CONNECTION_STRING: https://test.com
          SUPABASE_URL: https://test.com
          SUPABASE_PUBLISHABLE_KEY: test
          BETTER_AUTH_SECRET: test
          BETTER_AUTH_URL: https://test.com
          GEMINI_API_KEY: test
          GOOGLE_EMAIL: test@test.com
          GOOGLE_APP_PASSWORD: test
          FINNHUB_API_KEY: test
        run: |
          npx next typegen
          npx eslint ${{ steps.get-files-to-lint.outputs.all_changed_files }}
